#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ThemeName {
    Minimalist,
    Bold,
    Professional,
    Playful,
}

impl ThemeName {
    pub fn label(&self) -> &'static str {
        match self {
            ThemeName::Minimalist => "Minimalist",
            ThemeName::Bold => "Bold",
            ThemeName::Professional => "Professional",
            ThemeName::Playful => "Playful",
        }
    }

    pub const ALL: [ThemeName; 4] = [
        ThemeName::Minimalist,
        ThemeName::Bold,
        ThemeName::Professional,
        ThemeName::Playful,
    ];
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Mode {
    Light,
    Dark,
}

// Some fields are only accessed inside view! proc macros,
// which the dead_code analyzer cannot see through.
#[allow(dead_code)]
#[derive(Debug, Clone, Copy)]
pub struct ThemeColors {
    pub background: &'static str,
    pub card_bg: &'static str,
    pub card_border: &'static str,
    pub text_primary: &'static str,
    pub text_secondary: &'static str,
    pub text_muted: &'static str,
    pub segment_stroke: &'static str,
    pub ring_defaults: [&'static str; 5],
    pub ring_text_colors: [&'static str; 5],
    pub svg_bg: &'static str,
    pub svg_border: &'static str,
    pub center_circle_bg: &'static str,
    pub ring_divider: &'static str,
    pub now_highlight: &'static str,
    pub button_primary_bg: &'static str,
    pub button_primary_text: &'static str,
    pub button_secondary_bg: &'static str,
    pub input_border: &'static str,
    pub input_bg: &'static str,
    pub success_bg: &'static str,
    pub success_border: &'static str,
    pub success_text: &'static str,
    pub success_text_dark: &'static str,
    pub warning_bg: &'static str,
    pub warning_border: &'static str,
    pub warning_text: &'static str,
    pub warning_text_dark: &'static str,
    pub meeting_essential: &'static str,
    pub meeting_non_essential: &'static str,
}

pub fn get_theme(name: ThemeName, mode: Mode) -> &'static ThemeColors {
    match (name, mode) {
        (ThemeName::Minimalist, Mode::Light) => &MINIMALIST_LIGHT,
        (ThemeName::Minimalist, Mode::Dark) => &MINIMALIST_DARK,
        (ThemeName::Bold, Mode::Light) => &BOLD_LIGHT,
        (ThemeName::Bold, Mode::Dark) => &BOLD_DARK,
        (ThemeName::Professional, Mode::Light) => &PROFESSIONAL_LIGHT,
        (ThemeName::Professional, Mode::Dark) => &PROFESSIONAL_DARK,
        (ThemeName::Playful, Mode::Light) => &PLAYFUL_LIGHT,
        (ThemeName::Playful, Mode::Dark) => &PLAYFUL_DARK,
    }
}

static MINIMALIST_LIGHT: ThemeColors = ThemeColors {
    background: "#ffffff",
    card_bg: "#f9fafb",
    card_border: "#e5e7eb",
    text_primary: "#374151",
    text_secondary: "#6b7280",
    text_muted: "#9ca3af",
    segment_stroke: "#f9f9f9",
    ring_defaults: ["#ebebf0", "#ebebf0", "#ebebf0", "#ebebf0", "#ebebf0"],
    ring_text_colors: ["#007acc", "#007acc", "#007acc", "#007acc", "#007acc"],
    svg_bg: "#f9fafb",
    svg_border: "#e5e7eb",
    center_circle_bg: "#f8fafc",
    ring_divider: "#f9f9f9",
    now_highlight: "#007acc",
    button_primary_bg: "#007acc",
    button_primary_text: "#ffffff",
    button_secondary_bg: "#f3f4f6",
    input_border: "#e5e7eb",
    input_bg: "#ffffff",
    success_bg: "#f0fdf4",
    success_border: "#bbf7d0",
    success_text: "#16a34a",
    success_text_dark: "#166534",
    warning_bg: "#fef3c7",
    warning_border: "#fde68a",
    warning_text: "#d97706",
    warning_text_dark: "#92400e",
    meeting_essential: "#22c55e",
    meeting_non_essential: "#ec4899",
};

static MINIMALIST_DARK: ThemeColors = ThemeColors {
    background: "#1e1e1e",
    card_bg: "#252526",
    card_border: "#3c3c3c",
    text_primary: "#d4d4d4",
    text_secondary: "#9ca3af",
    text_muted: "#6b7280",
    segment_stroke: "#3c3c3c",
    ring_defaults: ["#2d2d35", "#2d2d35", "#2d2d35", "#2d2d35", "#2d2d35"],
    ring_text_colors: ["#007acc", "#007acc", "#007acc", "#007acc", "#007acc"],
    svg_bg: "#252526",
    svg_border: "#3c3c3c",
    center_circle_bg: "#2d2d30",
    ring_divider: "#3c3c3c",
    now_highlight: "#007acc",
    button_primary_bg: "#007acc",
    button_primary_text: "#ffffff",
    button_secondary_bg: "#3c3c3c",
    input_border: "#3c3c3c",
    input_bg: "#252526",
    success_bg: "#1a2e1a",
    success_border: "#2d4a2d",
    success_text: "#4ade80",
    success_text_dark: "#86efac",
    warning_bg: "#3d2e1a",
    warning_border: "#5a4520",
    warning_text: "#fbbf24",
    warning_text_dark: "#fcd34d",
    meeting_essential: "#22c55e",
    meeting_non_essential: "#ec4899",
};

static BOLD_LIGHT: ThemeColors = ThemeColors {
    background: "#ffffff",
    card_bg: "#ffffff",
    card_border: "#ec4899",
    text_primary: "#1f2937",
    text_secondary: "#374151",
    text_muted: "#6b7280",
    segment_stroke: "#f3f4f6",
    ring_defaults: ["#ebebf0", "#ebebf0", "#ebebf0", "#ebebf0", "#ebebf0"],
    ring_text_colors: ["#ec4899", "#3b82f6", "#84cc16", "#f59e0b", "#06b6d4"],
    svg_bg: "#ffffff",
    svg_border: "#ec4899",
    center_circle_bg: "#fdf2f8",
    ring_divider: "#f3f4f6",
    now_highlight: "#ec4899",
    button_primary_bg: "#ec4899",
    button_primary_text: "#ffffff",
    button_secondary_bg: "#f9fafb",
    input_border: "#ec4899",
    input_bg: "#ffffff",
    success_bg: "#f7fee7",
    success_border: "#d9f99d",
    success_text: "#65a30d",
    success_text_dark: "#4d7c0f",
    warning_bg: "#fef3c7",
    warning_border: "#fde68a",
    warning_text: "#d97706",
    warning_text_dark: "#92400e",
    meeting_essential: "#84cc16",
    meeting_non_essential: "#ec4899",
};

static BOLD_DARK: ThemeColors = ThemeColors {
    background: "#1e1e1e",
    card_bg: "#2d2d30",
    card_border: "#c586c0",
    text_primary: "#ffffff",
    text_secondary: "#d4d4d4",
    text_muted: "#9ca3af",
    segment_stroke: "#3c3c3c",
    ring_defaults: ["#2d2d35", "#2d2d35", "#2d2d35", "#2d2d35", "#2d2d35"],
    ring_text_colors: ["#c586c0", "#569cd6", "#ce9178", "#dcdcaa", "#4ec9b0"],
    svg_bg: "#252526",
    svg_border: "#c586c0",
    center_circle_bg: "#3d2d3a",
    ring_divider: "#3c3c3c",
    now_highlight: "#c586c0",
    button_primary_bg: "#c586c0",
    button_primary_text: "#ffffff",
    button_secondary_bg: "#3c3c3c",
    input_border: "#c586c0",
    input_bg: "#252526",
    success_bg: "#2a3520",
    success_border: "#3d4a2d",
    success_text: "#ce9178",
    success_text_dark: "#daa520",
    warning_bg: "#3d2e1a",
    warning_border: "#5a4520",
    warning_text: "#fbbf24",
    warning_text_dark: "#fcd34d",
    meeting_essential: "#ce9178",
    meeting_non_essential: "#c586c0",
};

static PROFESSIONAL_LIGHT: ThemeColors = ThemeColors {
    background: "#f8fafc",
    card_bg: "#ffffff",
    card_border: "#cbd5e1",
    text_primary: "#1e3a8a",
    text_secondary: "#374151",
    text_muted: "#64748b",
    segment_stroke: "#f1f5f9",
    ring_defaults: ["#ebebf0", "#ebebf0", "#ebebf0", "#ebebf0", "#ebebf0"],
    ring_text_colors: ["#1e3a8a", "#0ea5e9", "#f59e0b", "#16a34a", "#7c3aed"],
    svg_bg: "#ffffff",
    svg_border: "#cbd5e1",
    center_circle_bg: "#f8fafc",
    ring_divider: "#f1f5f9",
    now_highlight: "#0ea5e9",
    button_primary_bg: "#1e3a8a",
    button_primary_text: "#ffffff",
    button_secondary_bg: "#f1f5f9",
    input_border: "#cbd5e1",
    input_bg: "#ffffff",
    success_bg: "#f0fdf4",
    success_border: "#bbf7d0",
    success_text: "#16a34a",
    success_text_dark: "#166534",
    warning_bg: "#fef3c7",
    warning_border: "#fde68a",
    warning_text: "#d97706",
    warning_text_dark: "#92400e",
    meeting_essential: "#0ea5e9",
    meeting_non_essential: "#f59e0b",
};

static PROFESSIONAL_DARK: ThemeColors = ThemeColors {
    background: "#1e293b",
    card_bg: "#334155",
    card_border: "#475569",
    text_primary: "#e2e8f0",
    text_secondary: "#cbd5e1",
    text_muted: "#94a3b8",
    segment_stroke: "#475569",
    ring_defaults: ["#2d2d35", "#2d2d35", "#2d2d35", "#2d2d35", "#2d2d35"],
    ring_text_colors: ["#14b8a6", "#22d3ee", "#f59e0b", "#4ade80", "#a78bfa"],
    svg_bg: "#334155",
    svg_border: "#475569",
    center_circle_bg: "#1e293b",
    ring_divider: "#475569",
    now_highlight: "#14b8a6",
    button_primary_bg: "#14b8a6",
    button_primary_text: "#ffffff",
    button_secondary_bg: "#475569",
    input_border: "#475569",
    input_bg: "#334155",
    success_bg: "#1a3a3a",
    success_border: "#2d4a4a",
    success_text: "#5eead4",
    success_text_dark: "#99f6e4",
    warning_bg: "#3d2e1a",
    warning_border: "#5a4520",
    warning_text: "#fbbf24",
    warning_text_dark: "#fcd34d",
    meeting_essential: "#14b8a6",
    meeting_non_essential: "#f59e0b",
};

static PLAYFUL_LIGHT: ThemeColors = ThemeColors {
    background: "#fef3c7",
    card_bg: "#ffffff",
    card_border: "#e9d5ff",
    text_primary: "#7c2d12",
    text_secondary: "#92400e",
    text_muted: "#a16207",
    segment_stroke: "#fef3c7",
    ring_defaults: ["#ebebf0", "#ebebf0", "#ebebf0", "#ebebf0", "#ebebf0"],
    ring_text_colors: ["#ea580c", "#059669", "#a855f7", "#e11d48", "#0284c7"],
    svg_bg: "#fffbeb",
    svg_border: "#e9d5ff",
    center_circle_bg: "#fef3c7",
    ring_divider: "#fef3c7",
    now_highlight: "#a78bfa",
    button_primary_bg: "#a855f7",
    button_primary_text: "#ffffff",
    button_secondary_bg: "#fef3c7",
    input_border: "#e9d5ff",
    input_bg: "#ffffff",
    success_bg: "#d1fae5",
    success_border: "#a7f3d0",
    success_text: "#047857",
    success_text_dark: "#065f46",
    warning_bg: "#fed7aa",
    warning_border: "#fdba74",
    warning_text: "#c2410c",
    warning_text_dark: "#9a3412",
    meeting_essential: "#059669",
    meeting_non_essential: "#a855f7",
};

static PLAYFUL_DARK: ThemeColors = ThemeColors {
    background: "#2d2d30",
    card_bg: "#3a3a3c",
    card_border: "#bd63c5",
    text_primary: "#e2e8f0",
    text_secondary: "#cbd5e1",
    text_muted: "#94a3b8",
    segment_stroke: "#4a4a4c",
    ring_defaults: ["#2d2d35", "#2d2d35", "#2d2d35", "#2d2d35", "#2d2d35"],
    ring_text_colors: ["#ce9178", "#569cd6", "#bd63c5", "#4ec9b0", "#dcdcaa"],
    svg_bg: "#3a3a3c",
    svg_border: "#bd63c5",
    center_circle_bg: "#2d2d30",
    ring_divider: "#4a4a4c",
    now_highlight: "#bd63c5",
    button_primary_bg: "#bd63c5",
    button_primary_text: "#ffffff",
    button_secondary_bg: "#4a4a4c",
    input_border: "#bd63c5",
    input_bg: "#3a3a3c",
    success_bg: "#1a3a2a",
    success_border: "#2d4a3d",
    success_text: "#569cd6",
    success_text_dark: "#86bcf6",
    warning_bg: "#3d2e1a",
    warning_border: "#5a4520",
    warning_text: "#ce9178",
    warning_text_dark: "#daa520",
    meeting_essential: "#569cd6",
    meeting_non_essential: "#bd63c5",
};
