#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ThemeName {
    Minimalist,
    Bold,
    Professional,
    Playful,
}

impl ThemeName {
    pub fn label(&self) -> &'static str {
        match self {
            ThemeName::Minimalist => "Minimalist",
            ThemeName::Bold => "Bold",
            ThemeName::Professional => "Professional",
            ThemeName::Playful => "Playful",
        }
    }

    pub const ALL: [ThemeName; 4] = [
        ThemeName::Minimalist,
        ThemeName::Bold,
        ThemeName::Professional,
        ThemeName::Playful,
    ];
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Mode {
    Light,
    Dark,
}

#[derive(Debug, Clone, Copy)]
pub struct ThemeColors {
    pub background: &'static str,
    pub card_bg: &'static str,
    pub card_border: &'static str,
    pub text_primary: &'static str,
    pub text_secondary: &'static str,
    pub text_muted: &'static str,
    pub segment_default: &'static str,
    pub segment_stroke: &'static str,
    pub segment_overlap: &'static str,
    pub segment_dallas: &'static str,
    pub segment_connecticut: &'static str,
    pub segment_london: &'static str,
    pub svg_bg: &'static str,
    pub svg_border: &'static str,
    pub center_circle_bg: &'static str,
    pub center_circle_border: &'static str,
    pub ring_divider: &'static str,
    pub now_highlight: &'static str,
    pub now_line: &'static str,
    pub clock_text_outer: &'static str,
    pub clock_text_middle: &'static str,
    pub clock_text_inner: &'static str,
    pub clock_text_top: &'static str,
    pub button_primary_bg: &'static str,
    pub button_primary_text: &'static str,
    pub button_primary_hover: &'static str,
    pub button_secondary_bg: &'static str,
    pub button_secondary_text: &'static str,
    pub input_border: &'static str,
    pub input_bg: &'static str,
    pub success_bg: &'static str,
    pub success_border: &'static str,
    pub success_text: &'static str,
    pub success_text_dark: &'static str,
    pub warning_bg: &'static str,
    pub warning_border: &'static str,
    pub warning_text: &'static str,
    pub warning_text_dark: &'static str,
    pub meeting_essential: &'static str,
    pub meeting_non_essential: &'static str,
}

pub fn get_theme(name: ThemeName, mode: Mode) -> &'static ThemeColors {
    match (name, mode) {
        (ThemeName::Minimalist, Mode::Light) => &MINIMALIST_LIGHT,
        (ThemeName::Minimalist, Mode::Dark) => &MINIMALIST_DARK,
        (ThemeName::Bold, Mode::Light) => &BOLD_LIGHT,
        (ThemeName::Bold, Mode::Dark) => &BOLD_DARK,
        (ThemeName::Professional, Mode::Light) => &PROFESSIONAL_LIGHT,
        (ThemeName::Professional, Mode::Dark) => &PROFESSIONAL_DARK,
        (ThemeName::Playful, Mode::Light) => &PLAYFUL_LIGHT,
        (ThemeName::Playful, Mode::Dark) => &PLAYFUL_DARK,
    }
}

static MINIMALIST_LIGHT: ThemeColors = ThemeColors {
    background: "#ffffff",
    card_bg: "#f9fafb",
    card_border: "#e5e7eb",
    text_primary: "#374151",
    text_secondary: "#6b7280",
    text_muted: "#9ca3af",
    segment_default: "#ffffff",
    segment_stroke: "#f9f9f9",
    segment_overlap: "#007acc",
    segment_dallas: "#e5e7eb",
    segment_connecticut: "#d1d5db",
    segment_london: "#f3f4f6",
    svg_bg: "#f9fafb",
    svg_border: "#e5e7eb",
    center_circle_bg: "#f8fafc",
    center_circle_border: "#e2e8f0",
    ring_divider: "#f9f9f9",
    now_highlight: "#007acc",
    now_line: "#007acc",
    clock_text_outer: "#007acc",
    clock_text_middle: "#007acc",
    clock_text_inner: "#007acc",
    clock_text_top: "#6b7280",
    button_primary_bg: "#007acc",
    button_primary_text: "#ffffff",
    button_primary_hover: "#005a9e",
    button_secondary_bg: "#f3f4f6",
    button_secondary_text: "#6b7280",
    input_border: "#e5e7eb",
    input_bg: "#ffffff",
    success_bg: "#f0fdf4",
    success_border: "#bbf7d0",
    success_text: "#16a34a",
    success_text_dark: "#166534",
    warning_bg: "#fef3c7",
    warning_border: "#fde68a",
    warning_text: "#d97706",
    warning_text_dark: "#92400e",
    meeting_essential: "#22c55e",
    meeting_non_essential: "#ec4899",
};

static MINIMALIST_DARK: ThemeColors = ThemeColors {
    background: "#1e1e1e",
    card_bg: "#252526",
    card_border: "#3c3c3c",
    text_primary: "#d4d4d4",
    text_secondary: "#9ca3af",
    text_muted: "#6b7280",
    segment_default: "#2d2d30",
    segment_stroke: "#3c3c3c",
    segment_overlap: "#007acc",
    segment_dallas: "#3a3a3c",
    segment_connecticut: "#454545",
    segment_london: "#505050",
    svg_bg: "#252526",
    svg_border: "#3c3c3c",
    center_circle_bg: "#2d2d30",
    center_circle_border: "#3c3c3c",
    ring_divider: "#3c3c3c",
    now_highlight: "#007acc",
    now_line: "#007acc",
    clock_text_outer: "#007acc",
    clock_text_middle: "#007acc",
    clock_text_inner: "#007acc",
    clock_text_top: "#9ca3af",
    button_primary_bg: "#007acc",
    button_primary_text: "#ffffff",
    button_primary_hover: "#005a9e",
    button_secondary_bg: "#3c3c3c",
    button_secondary_text: "#9ca3af",
    input_border: "#3c3c3c",
    input_bg: "#252526",
    success_bg: "#1a2e1a",
    success_border: "#2d4a2d",
    success_text: "#4ade80",
    success_text_dark: "#86efac",
    warning_bg: "#3d2e1a",
    warning_border: "#5a4520",
    warning_text: "#fbbf24",
    warning_text_dark: "#fcd34d",
    meeting_essential: "#22c55e",
    meeting_non_essential: "#ec4899",
};

static BOLD_LIGHT: ThemeColors = ThemeColors {
    background: "#ffffff",
    card_bg: "#ffffff",
    card_border: "#ec4899",
    text_primary: "#1f2937",
    text_secondary: "#374151",
    text_muted: "#6b7280",
    segment_default: "#ffffff",
    segment_stroke: "#f3f4f6",
    segment_overlap: "#ec4899",
    segment_dallas: "#fce7f3",
    segment_connecticut: "#dbeafe",
    segment_london: "#ecfccb",
    svg_bg: "#ffffff",
    svg_border: "#ec4899",
    center_circle_bg: "#fdf2f8",
    center_circle_border: "#ec4899",
    ring_divider: "#f3f4f6",
    now_highlight: "#ec4899",
    now_line: "#1f2937",
    clock_text_outer: "#ec4899",
    clock_text_middle: "#3b82f6",
    clock_text_inner: "#84cc16",
    clock_text_top: "#1f2937",
    button_primary_bg: "#ec4899",
    button_primary_text: "#ffffff",
    button_primary_hover: "#db2777",
    button_secondary_bg: "#f9fafb",
    button_secondary_text: "#374151",
    input_border: "#ec4899",
    input_bg: "#ffffff",
    success_bg: "#f7fee7",
    success_border: "#d9f99d",
    success_text: "#65a30d",
    success_text_dark: "#4d7c0f",
    warning_bg: "#fef3c7",
    warning_border: "#fde68a",
    warning_text: "#d97706",
    warning_text_dark: "#92400e",
    meeting_essential: "#84cc16",
    meeting_non_essential: "#ec4899",
};

static BOLD_DARK: ThemeColors = ThemeColors {
    background: "#1e1e1e",
    card_bg: "#2d2d30",
    card_border: "#c586c0",
    text_primary: "#ffffff",
    text_secondary: "#d4d4d4",
    text_muted: "#9ca3af",
    segment_default: "#252526",
    segment_stroke: "#3c3c3c",
    segment_overlap: "#c586c0",
    segment_dallas: "#3d2d3a",
    segment_connecticut: "#2d3a4a",
    segment_london: "#3a3d2d",
    svg_bg: "#252526",
    svg_border: "#c586c0",
    center_circle_bg: "#3d2d3a",
    center_circle_border: "#c586c0",
    ring_divider: "#3c3c3c",
    now_highlight: "#c586c0",
    now_line: "#ffffff",
    clock_text_outer: "#c586c0",
    clock_text_middle: "#569cd6",
    clock_text_inner: "#ce9178",
    clock_text_top: "#d4d4d4",
    button_primary_bg: "#c586c0",
    button_primary_text: "#ffffff",
    button_primary_hover: "#bd63c5",
    button_secondary_bg: "#3c3c3c",
    button_secondary_text: "#d4d4d4",
    input_border: "#c586c0",
    input_bg: "#252526",
    success_bg: "#2a3520",
    success_border: "#3d4a2d",
    success_text: "#ce9178",
    success_text_dark: "#daa520",
    warning_bg: "#3d2e1a",
    warning_border: "#5a4520",
    warning_text: "#fbbf24",
    warning_text_dark: "#fcd34d",
    meeting_essential: "#ce9178",
    meeting_non_essential: "#c586c0",
};

static PROFESSIONAL_LIGHT: ThemeColors = ThemeColors {
    background: "#f8fafc",
    card_bg: "#ffffff",
    card_border: "#cbd5e1",
    text_primary: "#1e3a8a",
    text_secondary: "#374151",
    text_muted: "#64748b",
    segment_default: "#ffffff",
    segment_stroke: "#f1f5f9",
    segment_overlap: "#f59e0b",
    segment_dallas: "#dbeafe",
    segment_connecticut: "#e0e7ff",
    segment_london: "#fef3c7",
    svg_bg: "#ffffff",
    svg_border: "#cbd5e1",
    center_circle_bg: "#f8fafc",
    center_circle_border: "#cbd5e1",
    ring_divider: "#f1f5f9",
    now_highlight: "#0ea5e9",
    now_line: "#1e3a8a",
    clock_text_outer: "#1e3a8a",
    clock_text_middle: "#0ea5e9",
    clock_text_inner: "#f59e0b",
    clock_text_top: "#64748b",
    button_primary_bg: "#1e3a8a",
    button_primary_text: "#ffffff",
    button_primary_hover: "#1e40af",
    button_secondary_bg: "#f1f5f9",
    button_secondary_text: "#374151",
    input_border: "#cbd5e1",
    input_bg: "#ffffff",
    success_bg: "#f0fdf4",
    success_border: "#bbf7d0",
    success_text: "#16a34a",
    success_text_dark: "#166534",
    warning_bg: "#fef3c7",
    warning_border: "#fde68a",
    warning_text: "#d97706",
    warning_text_dark: "#92400e",
    meeting_essential: "#0ea5e9",
    meeting_non_essential: "#f59e0b",
};

static PROFESSIONAL_DARK: ThemeColors = ThemeColors {
    background: "#1e293b",
    card_bg: "#334155",
    card_border: "#475569",
    text_primary: "#e2e8f0",
    text_secondary: "#cbd5e1",
    text_muted: "#94a3b8",
    segment_default: "#334155",
    segment_stroke: "#475569",
    segment_overlap: "#14b8a6",
    segment_dallas: "#1e3a5f",
    segment_connecticut: "#1e2f4a",
    segment_london: "#3a3520",
    svg_bg: "#334155",
    svg_border: "#475569",
    center_circle_bg: "#1e293b",
    center_circle_border: "#475569",
    ring_divider: "#475569",
    now_highlight: "#14b8a6",
    now_line: "#e2e8f0",
    clock_text_outer: "#14b8a6",
    clock_text_middle: "#22d3ee",
    clock_text_inner: "#f59e0b",
    clock_text_top: "#cbd5e1",
    button_primary_bg: "#14b8a6",
    button_primary_text: "#ffffff",
    button_primary_hover: "#0d9488",
    button_secondary_bg: "#475569",
    button_secondary_text: "#cbd5e1",
    input_border: "#475569",
    input_bg: "#334155",
    success_bg: "#1a3a3a",
    success_border: "#2d4a4a",
    success_text: "#5eead4",
    success_text_dark: "#99f6e4",
    warning_bg: "#3d2e1a",
    warning_border: "#5a4520",
    warning_text: "#fbbf24",
    warning_text_dark: "#fcd34d",
    meeting_essential: "#14b8a6",
    meeting_non_essential: "#f59e0b",
};

static PLAYFUL_LIGHT: ThemeColors = ThemeColors {
    background: "#fef3c7",
    card_bg: "#ffffff",
    card_border: "#e9d5ff",
    text_primary: "#7c2d12",
    text_secondary: "#92400e",
    text_muted: "#a16207",
    segment_default: "#ffffff",
    segment_stroke: "#fef3c7",
    segment_overlap: "#a78bfa",
    segment_dallas: "#fed7aa",
    segment_connecticut: "#d1fae5",
    segment_london: "#e9d5ff",
    svg_bg: "#fffbeb",
    svg_border: "#e9d5ff",
    center_circle_bg: "#fef3c7",
    center_circle_border: "#e9d5ff",
    ring_divider: "#fef3c7",
    now_highlight: "#a78bfa",
    now_line: "#7c2d12",
    clock_text_outer: "#ea580c",
    clock_text_middle: "#059669",
    clock_text_inner: "#a855f7",
    clock_text_top: "#92400e",
    button_primary_bg: "#a855f7",
    button_primary_text: "#ffffff",
    button_primary_hover: "#9333ea",
    button_secondary_bg: "#fef3c7",
    button_secondary_text: "#92400e",
    input_border: "#e9d5ff",
    input_bg: "#ffffff",
    success_bg: "#d1fae5",
    success_border: "#a7f3d0",
    success_text: "#047857",
    success_text_dark: "#065f46",
    warning_bg: "#fed7aa",
    warning_border: "#fdba74",
    warning_text: "#c2410c",
    warning_text_dark: "#9a3412",
    meeting_essential: "#059669",
    meeting_non_essential: "#a855f7",
};

static PLAYFUL_DARK: ThemeColors = ThemeColors {
    background: "#2d2d30",
    card_bg: "#3a3a3c",
    card_border: "#bd63c5",
    text_primary: "#e2e8f0",
    text_secondary: "#cbd5e1",
    text_muted: "#94a3b8",
    segment_default: "#3a3a3c",
    segment_stroke: "#4a4a4c",
    segment_overlap: "#bd63c5",
    segment_dallas: "#4a3520",
    segment_connecticut: "#204a3a",
    segment_london: "#3d204a",
    svg_bg: "#3a3a3c",
    svg_border: "#bd63c5",
    center_circle_bg: "#2d2d30",
    center_circle_border: "#bd63c5",
    ring_divider: "#4a4a4c",
    now_highlight: "#bd63c5",
    now_line: "#e2e8f0",
    clock_text_outer: "#ce9178",
    clock_text_middle: "#569cd6",
    clock_text_inner: "#bd63c5",
    clock_text_top: "#cbd5e1",
    button_primary_bg: "#bd63c5",
    button_primary_text: "#ffffff",
    button_primary_hover: "#a855f7",
    button_secondary_bg: "#4a4a4c",
    button_secondary_text: "#cbd5e1",
    input_border: "#bd63c5",
    input_bg: "#3a3a3c",
    success_bg: "#1a3a2a",
    success_border: "#2d4a3d",
    success_text: "#569cd6",
    success_text_dark: "#86bcf6",
    warning_bg: "#3d2e1a",
    warning_border: "#5a4520",
    warning_text: "#ce9178",
    warning_text_dark: "#daa520",
    meeting_essential: "#569cd6",
    meeting_non_essential: "#bd63c5",
};
