use crate::modules::types::TimezoneEntry;

pub static TIMEZONE_DATABASE: &[TimezoneEntry] = &[
    TimezoneEntry { id: "pacific_baker", name: "Baker Island", short_name: "BAKT", utc_offset: -12.0 },
    TimezoneEntry { id: "pacific_samoa", name: "Pago Pago (SST)", short_name: "PPG", utc_offset: -11.0 },
    TimezoneEntry { id: "pacific_honolulu", name: "Honolulu (HST)", short_name: "HNL", utc_offset: -10.0 },
    TimezoneEntry { id: "pacific_marquesas", name: "Marquesas Islands", short_name: "MART", utc_offset: -9.5 },
    TimezoneEntry { id: "america_anchorage", name: "Anchorage (AKST)", short_name: "ANC", utc_offset: -9.0 },
    TimezoneEntry { id: "america_los_angeles", name: "Los Angeles (PST)", short_name: "LAX", utc_offset: -8.0 },
    TimezoneEntry { id: "america_denver", name: "Denver (MST)", short_name: "DEN", utc_offset: -7.0 },
    TimezoneEntry { id: "america_chicago", name: "Dallas (CST)", short_name: "DAL", utc_offset: -6.0 },
    TimezoneEntry { id: "america_new_york", name: "New York (EST)", short_name: "NYC", utc_offset: -5.0 },
    TimezoneEntry { id: "america_caracas", name: "Caracas (VET)", short_name: "CCS", utc_offset: -4.0 },
    TimezoneEntry { id: "america_st_johns", name: "St. John's (NST)", short_name: "YYT", utc_offset: -3.5 },
    TimezoneEntry { id: "america_sao_paulo", name: "São Paulo (BRT)", short_name: "GRU", utc_offset: -3.0 },
    TimezoneEntry { id: "atlantic_south_georgia", name: "South Georgia", short_name: "GSI", utc_offset: -2.0 },
    TimezoneEntry { id: "atlantic_azores", name: "Azores (AZOT)", short_name: "AZO", utc_offset: -1.0 },
    TimezoneEntry { id: "europe_london", name: "London (GMT)", short_name: "LON", utc_offset: 0.0 },
    TimezoneEntry { id: "europe_paris", name: "Paris (CET)", short_name: "PAR", utc_offset: 1.0 },
    TimezoneEntry { id: "europe_berlin", name: "Berlin (CET)", short_name: "BER", utc_offset: 1.0 },
    TimezoneEntry { id: "africa_cairo", name: "Cairo (EET)", short_name: "CAI", utc_offset: 2.0 },
    TimezoneEntry { id: "europe_moscow", name: "Moscow (MSK)", short_name: "MOW", utc_offset: 3.0 },
    TimezoneEntry { id: "asia_tehran", name: "Tehran (IRST)", short_name: "THR", utc_offset: 3.5 },
    TimezoneEntry { id: "asia_dubai", name: "Dubai (GST)", short_name: "DXB", utc_offset: 4.0 },
    TimezoneEntry { id: "asia_kabul", name: "Kabul (AFT)", short_name: "KBL", utc_offset: 4.5 },
    TimezoneEntry { id: "asia_karachi", name: "Karachi (PKT)", short_name: "KHI", utc_offset: 5.0 },
    TimezoneEntry { id: "asia_kolkata", name: "India (IST)", short_name: "DEL", utc_offset: 5.5 },
    TimezoneEntry { id: "asia_kathmandu", name: "Kathmandu (NPT)", short_name: "KTM", utc_offset: 5.75 },
    TimezoneEntry { id: "asia_dhaka", name: "Dhaka (BST)", short_name: "DAC", utc_offset: 6.0 },
    TimezoneEntry { id: "asia_yangon", name: "Yangon (MMT)", short_name: "RGN", utc_offset: 6.5 },
    TimezoneEntry { id: "asia_bangkok", name: "Bangkok (ICT)", short_name: "BKK", utc_offset: 7.0 },
    TimezoneEntry { id: "asia_shanghai", name: "Shanghai (CST)", short_name: "SHA", utc_offset: 8.0 },
    TimezoneEntry { id: "asia_hong_kong", name: "Hong Kong (HKT)", short_name: "HKG", utc_offset: 8.0 },
    TimezoneEntry { id: "asia_singapore", name: "Singapore (SGT)", short_name: "SIN", utc_offset: 8.0 },
    TimezoneEntry { id: "australia_eucla", name: "Eucla (ACWST)", short_name: "EUCL", utc_offset: 8.75 },
    TimezoneEntry { id: "asia_tokyo", name: "Tokyo (JST)", short_name: "TYO", utc_offset: 9.0 },
    TimezoneEntry { id: "australia_darwin", name: "Darwin (ACST)", short_name: "DRW", utc_offset: 9.5 },
    TimezoneEntry { id: "australia_sydney", name: "Sydney (AEST)", short_name: "SYD", utc_offset: 10.0 },
    TimezoneEntry { id: "australia_lhi", name: "Lord Howe Island", short_name: "LDH", utc_offset: 10.5 },
    TimezoneEntry { id: "pacific_noumea", name: "Nouméa (NCT)", short_name: "NOU", utc_offset: 11.0 },
    TimezoneEntry { id: "pacific_auckland", name: "Auckland (NZST)", short_name: "AKL", utc_offset: 12.0 },
    TimezoneEntry { id: "pacific_chatham", name: "Chatham Islands", short_name: "CHT", utc_offset: 12.75 },
    TimezoneEntry { id: "pacific_tongatapu", name: "Tonga (TOT)", short_name: "TBU", utc_offset: 13.0 },
    TimezoneEntry { id: "pacific_kiritimati", name: "Kiritimati (LINT)", short_name: "CXI", utc_offset: 14.0 },
];
